name: 'My Custom Action'
description: 'An example action with custom branding'
on:
 workflow_dispatch:
inputs:
  my-input:
    description: 'An input parameter'
    required: true
    default: 'default value'
outputs:
  my-output:
    description: 'An output value'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'zap'
  color: 'green'

